"""user update

Revision ID: 26eef447bf8a
Revises: aa723ba6e0ff
Create Date: 2024-06-09 21:37:21.789130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26eef447bf8a'
down_revision: Union[str, None] = 'aa723ba6e0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
